package com.engineeringlens.repository;

import java.util.UUID;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * One file in an imported repository's inventory (table "repository_files"). Path and size only;
 * file contents are fetched later, by the analysis phase, for relevant files.
 */
@Entity
@Table(name = "repository_files")
public class RepoFile {

    // Generated by Hibernate at insert time, so new rows are inserted directly (and batched)
    // instead of Spring Data first SELECTing to check whether a pre-set id already exists.
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @Column(name = "repository_id", nullable = false)
    private UUID repositoryId;

    @Column(nullable = false)
    private String path;

    @Column(name = "file_name", nullable = false)
    private String fileName;

    private String extension;

    private String language;

    @Column(name = "size_bytes", nullable = false)
    private long sizeBytes;

    @Column(nullable = false)
    private boolean ignored;

    @Column(name = "ignore_reason")
    private String ignoreReason;

    protected RepoFile() {
    }

    RepoFile(UUID repositoryId, FileClassifier.Classification c) {
        this.repositoryId = repositoryId;
        this.path = c.path();
        this.fileName = c.fileName();
        this.extension = c.extension();
        this.language = c.language();
        this.sizeBytes = c.sizeBytes();
        this.ignored = c.ignored();
        this.ignoreReason = c.ignoreReason();
    }

    public String getPath() { return path; }
    public String getFileName() { return fileName; }
    public String getExtension() { return extension; }
    public String getLanguage() { return language; }
    public long getSizeBytes() { return sizeBytes; }
    public boolean isIgnored() { return ignored; }
    public String getIgnoreReason() { return ignoreReason; }
}
