import type { LabAssessmentReport, LabHistoryItem, RunResult, ScenarioDetail, ScenarioLab, ScenarioSummary } from '../api'

export const scenarioSummary = (overrides: Partial<ScenarioSummary> = {}): ScenarioSummary => ({
  id: 'sc-1',
  position: 1,
  title: 'Prevent duplicate orders under retries',
  role: 'BACKEND_ENGINEER',
  category: 'CONCURRENCY_CONSISTENCY',
  difficulty: 'INTERMEDIATE',
  executionCapability: 'CODE',
  language: 'PYTHON',
  submitted: false,
  evaluationStatus: null,
  ...overrides,
})

export const lab = (overrides: Partial<ScenarioLab> = {}): ScenarioLab => ({
  id: 'lab-1',
  repositoryId: 'repo-1',
  repositoryName: 'orders-api',
  repositoryUrl: 'https://github.com/asha/orders-api',
  reviewId: 'rev-1',
  commitSha: 'c0ffee1234567',
  roles: ['BACKEND_ENGINEER'],
  seniority: 'SDE2',
  scenarioCount: 5,
  scenariosReady: 5,
  status: 'ACTIVE',
  errorCode: null,
  errorMessage: null,
  createdAt: '2026-10-04T10:00:00Z',
  completedAt: null,
  scenarios: [scenarioSummary()],
  generationStage: 'DONE',
  scenariosRejected: 0,
  generationNote: null,
  ...overrides,
})

export const STARTER = 'def place(order, store):\n    store.append(order)\n    return order\n'

export const scenarioDetail = (overrides: Partial<ScenarioDetail> = {}): ScenarioDetail => ({
  id: 'sc-1',
  labId: 'lab-1',
  position: 1,
  scenarioCount: 5,
  repositoryName: 'orders-api',
  commitSha: 'c0ffee1234567',
  title: 'Prevent duplicate orders under retries',
  role: 'BACKEND_ENGINEER',
  seniority: 'SDE2',
  category: 'CONCURRENCY_CONSISTENCY',
  difficulty: 'INTERMEDIATE',
  executionCapability: 'CODE',
  language: 'PYTHON',
  document: {
    scenarioSchemaVersion: 1,
    title: 'Prevent duplicate orders under retries',
    summary: 'Retried checkout requests create duplicate orders.',
    incident: 'Customers who double-click Pay see two identical orders.',
    context: 'place() in app/services/orders.py stores orders in a list.',
    task: 'Make place() safe to call twice with the same order.',
    expectedBehaviour: ['A repeated request returns the existing order'],
    constraints: ['Keep the function signature'],
    evidence: [{ file: 'app/services/orders.py', lineStart: 2, lineEnd: 2, explanation: 'Appends unconditionally' }],
  },
  files: [
    { path: 'orders.py', editable: true, starterContent: STARTER, content: STARTER },
    { path: 'store.py', editable: false, starterContent: 'STORE = []\n', content: 'STORE = []\n' },
  ],
  draftMode: 'CODE',
  draftApproach: null,
  draftUpdatedAt: null,
  submitted: false,
  evaluationStatus: null,
  ...overrides,
})

export const runResult = (overrides: Partial<RunResult> = {}): RunResult => ({
  status: 'FAILED',
  passed: 2,
  total: 3,
  durationMs: 812,
  checks: [
    { name: 'places an order', passed: true, message: null, durationMs: 2 },
    { name: 'ignores a repeated request', passed: false, message: 'a repeated request created a second order', durationMs: 2 },
    { name: 'keeps different orders apart', passed: true, message: null, durationMs: 1 },
  ],
  message: null,
  stdout: 'placing 1',
  stderr: '',
  outputTruncated: false,
  ...overrides,
})

export const historyItem = (overrides: Partial<LabHistoryItem> = {}): LabHistoryItem => ({
  id: 'lab-1',
  number: 1,
  roles: ['BACKEND_ENGINEER'],
  seniority: 'SDE2',
  scenarioCount: 5,
  scenariosCompleted: 5,
  commitSha: 'c0ffee1234567',
  reviewId: 'rev-1',
  completedAt: '2026-10-04T12:00:00Z',
  scenariosGenerated: 5,
  ...overrides,
})

export const assessmentReport = (overrides: Partial<LabAssessmentReport> = {}): LabAssessmentReport => ({
  id: 'lab-1',
  number: 3,
  repositoryId: 'repo-1',
  repositoryName: 'orders-api',
  repositoryUrl: 'https://github.com/asha/orders-api',
  reviewId: 'rev-1',
  commitSha: 'c0ffee1234567',
  roles: ['BACKEND_ENGINEER'],
  seniority: 'SDE2',
  scenarioCount: 5,
  createdAt: '2026-10-04T10:00:00Z',
  completedAt: '2026-10-24T12:00:00Z',
  assessment: {
    overallAssessment: { summary: 'Correct fixes with gaps under concurrency.', engineeringLevel: 'Meets SDE2 expectations on correctness.', confidence: 'MEDIUM' },
    strengths: ['Correct fixes'],
    growthAreas: ['Concurrency'],
    scenarioLearning: [],
    learningRecommendations: [{ topic: 'Idempotency', why: 'Retries are everywhere', connectionToProject: 'Checkout in orders.py' }],
    limitations: ['Five scenarios is a small sample'],
    personalizedFor: 'Undergraduate, year 2',
  },
  scenarios: [
    {
      scenarioId: 'sc-1',
      position: 1,
      title: 'Prevent duplicate orders under retries',
      role: 'BACKEND_ENGINEER',
      category: 'CONCURRENCY_CONSISTENCY',
      difficulty: 'INTERMEDIATE',
      executionCapability: 'CODE',
      language: 'PYTHON',
      document: scenarioDetail().document,
      mode: 'CODE',
      submittedFiles: [{ path: 'orders.py', content: 'def place(order, store):\n    if order in store:\n        return order\n' }],
      submittedApproach: 'Return the existing order on a retry.',
      runResult: runResult({ status: 'PASSED', passed: 3 }),
      evaluation: {
        verdict: 'SOLID',
        confidence: 'MEDIUM',
        assessment: 'The fix prevents duplicates for sequential retries.',
        whatWasCorrect: ['Checks for an existing order'],
        whatWasMissed: ['Concurrent requests can still race'],
        rootCause: 'Order creation is not idempotent.',
        engineeringJudgment: 'Sound for one process.',
        tradeoffs: ['A list scan is O(n)'],
        scaleImpact: 'Needs a unique constraint under load.',
        regressionRisk: 'Low.',
        testingAssessment: 'Add a concurrent retry test.',
        recommendedFix: 'Enforce uniqueness where the data lives.',
        referenceApproach: 'Idempotency key plus unique index.',
      },
      reference: { expectedConcepts: ['idempotency'], referenceReasoning: 'Make creation idempotent.', solution: null },
      learningPoints: ['Learn how unique constraints make retries safe'],
      submittedAt: '2026-10-24T11:00:00Z',
    },
  ],
  scenariosGenerated: 5,
  generationNote: null,
  ...overrides,
})
